"""hypothesis_registry.py — SHAP hypothesis registry.

Collects research hypotheses generated by SHAP analyses.
Each hypothesis is a DISCOVERY ONLY — must go through L4/L5/L6 FDR validation.
Never auto-convert to EA rules.
"""
from __future__ import annotations
import datetime as dt
import json
import uuid
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Any


@dataclass
class SHAPHypothesis:
    """One SHAP-derived research hypothesis."""
    hypothesis_id: str
    experiment_id: str
    source: str                  # "SHAP-A" | "SHAP-B" | "SHAP-C" | "SHAP-D" | "SHAP-E" | "SHAP-G" | "SHAP-H"
    feature: str
    category: str                # feature category from contract
    hypothesis_type: str         # "importance" | "dependence" | "interaction" | "trigger_conditional" | "regime_conditional" | "execution_policy" | "stability"
    suggested_direction: int     # +1 / -1 / 0
    suggested_shape: str         # "MONO_UP" | "MONO_DOWN" | "BAND" | "UNKNOWN"
    evidence_strength: float     # mean |SHAP| or lift metric
    n_samples: int
    description: str
    metadata: Dict[str, Any] = field(default_factory=dict)
    status: str = "DISCOVERY_ONLY"    # always starts here
    created_at: str = ""
    # validation fields (filled by L4/L5/L6 later)
    validation_status: Optional[str] = None
    validation_experiment_id: Optional[str] = None

    def __post_init__(self):
        if not self.created_at:
            object.__setattr__(self, 'created_at', dt.datetime.utcnow().isoformat() + "Z")

    def to_dict(self) -> dict:
        return asdict(self)


class HypothesisRegistry:
    """Collects and serializes SHAP hypotheses."""

    def __init__(self, experiment_id: str):
        self.experiment_id = experiment_id
        self._hypotheses: List[SHAPHypothesis] = []

    def register(self, hyp: SHAPHypothesis) -> None:
        self._hypotheses.append(hyp)

    def register_from_dict(self, d: dict) -> None:
        """Register hypothesis from a dict (as returned by SHAP analysis functions)."""
        hyp_id = f"SHAP-H{len(self._hypotheses)+1:04d}-{uuid.uuid4().hex[:6]}"
        hyp = SHAPHypothesis(
            hypothesis_id=hyp_id,
            experiment_id=self.experiment_id,
            source=d.get("source", "SHAP-?"),
            feature=d.get("feature", "unknown"),
            category=d.get("category", "unknown"),
            hypothesis_type=d.get("hypothesis_type", "unknown"),
            suggested_direction=int(d.get("suggested_direction", 0)),
            suggested_shape=d.get("suggested_shape", "UNKNOWN"),
            evidence_strength=float(d.get("evidence_strength", 0.0)),
            n_samples=int(d.get("n_samples") or 0),
            description=d.get("description", ""),
            metadata=d.get("metadata", {}),
            status="DISCOVERY_ONLY",
        )
        self._hypotheses.append(hyp)

    def register_many(self, hyps: List[dict]) -> None:
        for h in hyps:
            self.register_from_dict(h)

    def __len__(self) -> int:
        return len(self._hypotheses)

    def to_list(self) -> List[dict]:
        return [h.to_dict() for h in self._hypotheses]

    def save(self, output_dir: Path) -> None:
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

        # JSON
        with (output_dir / "hypotheses.json").open("w", encoding="utf-8") as fh:
            json.dump(self.to_list(), fh, indent=2, default=str)

        # CSV summary
        try:
            import pandas as pd
            rows = []
            for h in self._hypotheses:
                rows.append({
                    "hypothesis_id": h.hypothesis_id,
                    "source": h.source,
                    "feature": h.feature,
                    "hypothesis_type": h.hypothesis_type,
                    "suggested_shape": h.suggested_shape,
                    "suggested_direction": h.suggested_direction,
                    "evidence_strength": round(h.evidence_strength, 4),
                    "n_samples": h.n_samples,
                    "status": h.status,
                    "description": h.description[:120],
                })
            pd.DataFrame(rows).to_csv(output_dir / "hypotheses.csv", index=False)
        except Exception as e:
            print(f"  [WARN] Could not write hypotheses.csv: {e}")

        print(f"  [Hypotheses] {len(self._hypotheses)} registered → {output_dir}")
