"""
nodes.py — Individual pipeline step implementations for VP EA.

Each function is a LangGraph node that performs one step of the automation cycle:
  1. compile_ea     — Compile Main_VP_EA.mq5 via MetaEditor CLI
  2. run_backtest   — Execute backtest via Terminal CLI
  3. check_data     — Verify sufficient VP_Funnel / VP_Trades data was generated
  4. run_analysis   — Execute run_all.py (VP quant research pipeline)
  5. verify_guards  — Confirm VPEdgeGuardConfig.mqh was regenerated
"""
import subprocess
import sys
import time
import glob
from pathlib import Path
from datetime import datetime

from config import (
    MT5_TERMINAL_EXE, MT5_METAEDITOR_EXE, MT5_DATA_DIR,
    MAIN_EA_SOURCE, EDGE_GUARD_CONFIG, RUN_ALL_SCRIPT,
    MT5_COMMON_FILES, MT5_LOCAL_FILES, RESEARCH_DIR,
    BACKTEST_CONFIG, COMPILE_TIMEOUT_SEC, BACKTEST_TIMEOUT_SEC,
    MIN_TRADES_FOR_ANALYSIS, ANALYSIS_TIMEOUT_SEC,
    BACKTEST_REPORT_DIR,
)


def compile_ea(state: dict) -> dict:
    """Compile Main_VP_EA.mq5 using MetaEditor64 CLI."""
    print("\n" + "=" * 60)
    print("  STEP: COMPILE VP EA")
    print("=" * 60)

    mql5_root = str(MT5_DATA_DIR / "MQL5")
    cmd = [
        str(MT5_METAEDITOR_EXE),
        f'/compile:{MAIN_EA_SOURCE}',
        '/log',
        f'/inc:{mql5_root}',
    ]
    print(f"  CMD: metaeditor64.exe /compile:...Main_VP_EA.mq5 /log /inc:...MQL5")

    log_file = MAIN_EA_SOURCE.with_suffix(".log")
    if log_file.exists():
        log_file.unlink()

    ex5_file = MAIN_EA_SOURCE.with_suffix(".ex5")
    ex5_mtime_before = ex5_file.stat().st_mtime if ex5_file.exists() else 0

    result = subprocess.run(cmd, capture_output=True, text=True, timeout=COMPILE_TIMEOUT_SEC)
    print(f"  Exit code: {result.returncode}")

    import time as _time
    _time.sleep(2)

    errors = 0
    warnings = 0
    if log_file.exists():
        try:
            log_content = log_file.read_text(encoding="utf-16-le", errors="replace")
        except Exception:
            log_content = log_file.read_text(encoding="utf-8", errors="replace")

        for line in log_content.splitlines():
            ll = line.lower()
            if "error" in ll and "0 error" not in ll and "result" not in ll:
                errors += 1
            if "warning" in ll and "0 warning" not in ll:
                warnings += 1

        lines = log_content.strip().splitlines()
        print(f"  Log ({len(lines)} lines):")
        for ln in lines[-15:]:
            print(f"    {ln.strip()}")

        for line in lines:
            if "Result:" in line or "result:" in line.lower():
                print(f"  >>> {line.strip()}")
                if "0 error" in line.lower():
                    errors = 0
    else:
        print("  [WARN] No .log file generated by MetaEditor")

    compiled_ok = False
    if ex5_file.exists():
        ex5_mtime_after = ex5_file.stat().st_mtime
        if ex5_mtime_after > ex5_mtime_before:
            compiled_ok = True
            print(f"  [OK] .ex5 file UPDATED")
        else:
            if errors == 0 and ex5_file.exists():
                compiled_ok = True
                print(f"  [OK] Assuming compilation succeeded (no errors, .ex5 exists)")
            else:
                print(f"  [WARN] .ex5 file NOT updated")

    state["compile_success"] = compiled_ok
    state["compile_errors"] = errors
    state["compile_warnings"] = warnings
    state["last_step"] = "compile_ea"

    if not state["compile_success"]:
        state["error"] = f"Compilation failed ({errors} errors, .ex5 not updated)"
        print(f"  [FAIL] {state['error']}")
    else:
        print(f"  [OK] Compiled successfully ({warnings} warnings)")

    return state


def run_backtest(state: dict) -> dict:
    """Run MT5 backtest using Terminal CLI."""
    print("\n" + "=" * 60)
    print("  STEP: RUN BACKTEST")
    print("=" * 60)

    if not state.get("compile_success"):
        state["error"] = "Skipping backtest — compilation failed"
        state["backtest_success"] = False
        print(f"  [SKIP] {state['error']}")
        return state

    ini_path = _generate_tester_ini()
    print(f"  Tester INI: {ini_path}")

    cmd = [str(MT5_TERMINAL_EXE), f"/config:{ini_path}"]
    print(f"  CMD: terminal64.exe /config:tester_config.ini")
    print(f"  Timeout: {BACKTEST_TIMEOUT_SEC}s ({BACKTEST_TIMEOUT_SEC//60} min)")
    print(f"  NOTE: MT5 will run backtest then auto-close (ShutdownTerminal=1)")
    print(f"  IMPORTANT: Close ALL other MT5 instances before running!")

    start_time = time.time()
    process = subprocess.Popen(cmd)

    try:
        process.wait(timeout=BACKTEST_TIMEOUT_SEC)
    except subprocess.TimeoutExpired:
        process.kill()
        state["error"] = "Backtest timed out"
        state["backtest_success"] = False
        print(f"  [FAIL] {state['error']}")
        return state

    elapsed = time.time() - start_time
    print(f"  Backtest completed in {elapsed:.0f}s")

    _move_backtest_report()

    state["backtest_success"] = True
    state["backtest_duration_sec"] = elapsed
    state["last_step"] = "run_backtest"
    print(f"  [OK] Backtest finished")
    return state


def check_data(state: dict) -> dict:
    """Verify that sufficient VP_Trades / VP_Funnel data exists for analysis."""
    print("\n" + "=" * 60)
    print("  STEP: CHECK DATA")
    print("=" * 60)

    if not state.get("backtest_success"):
        state["error"] = "Skipping data check — backtest failed"
        state["data_sufficient"] = False
        print(f"  [SKIP] {state['error']}")
        return state

    total_trades = 0
    trade_files = []

    # VP EA writes VP_Trades_*.csv
    for dir_path in [MT5_COMMON_FILES, MT5_LOCAL_FILES]:
        for f in glob.glob(str(dir_path / "VP_Trades_*.csv")):
            try:
                with open(f, "r", encoding="utf-16") as fh:
                    n_lines = sum(1 for _ in fh) - 1  # minus header
                if n_lines > 0:
                    total_trades += n_lines
                    trade_files.append((Path(f).name, n_lines))
            except Exception:
                try:
                    with open(f, "r", encoding="utf-8", errors="replace") as fh:
                        n_lines = sum(1 for _ in fh) - 1
                    if n_lines > 0:
                        total_trades += n_lines
                        trade_files.append((Path(f).name, n_lines))
                except Exception:
                    pass

    # VP EA writes VP_Funnel_*.csv
    total_funnel = 0
    for dir_path in [MT5_COMMON_FILES, MT5_LOCAL_FILES]:
        for f in glob.glob(str(dir_path / "VP_Funnel_*.csv")):
            try:
                with open(f, "r", encoding="utf-16") as fh:
                    n_lines = sum(1 for _ in fh) - 1
                if n_lines > 0:
                    total_funnel += n_lines
            except Exception:
                pass

    print(f"  VP_Trades: {total_trades} trades across {len(trade_files)} symbols")
    print(f"  VP_Funnel: {total_funnel} setups")
    if trade_files:
        trade_files.sort(key=lambda x: -x[1])
        for name, n in trade_files[:5]:
            print(f"    {name}: {n} trades")

    sufficient = total_trades >= MIN_TRADES_FOR_ANALYSIS
    state["data_sufficient"] = sufficient
    state["total_trades"] = total_trades
    state["total_funnel"] = total_funnel
    state["last_step"] = "check_data"

    if not sufficient:
        state["error"] = f"Insufficient data: {total_trades} trades (need {MIN_TRADES_FOR_ANALYSIS}+)"
        print(f"  [FAIL] {state['error']}")
    else:
        print(f"  [OK] Sufficient data for analysis")

    return state


def run_analysis(state: dict) -> dict:
    """Execute run_all.py to analyze VP data and generate VPEdgeGuardConfig."""
    print("\n" + "=" * 60)
    print("  STEP: RUN ANALYSIS (run_all.py)")
    print("=" * 60)

    if not state.get("data_sufficient"):
        state["error"] = "Skipping analysis — insufficient data"
        state["analysis_success"] = False
        print(f"  [SKIP] {state['error']}")
        return state

    guard_mtime_before = None
    if EDGE_GUARD_CONFIG.exists():
        guard_mtime_before = EDGE_GUARD_CONFIG.stat().st_mtime

    import os
    env = os.environ.copy()
    env["PYTHONIOENCODING"] = "utf-8"

    python_exe = sys.executable
    cmd = [python_exe, str(RUN_ALL_SCRIPT)]
    print(f"  CMD: {python_exe} run_all.py")
    print(f"  CWD: {RESEARCH_DIR}")
    print(f"  Timeout: {ANALYSIS_TIMEOUT_SEC}s ({ANALYSIS_TIMEOUT_SEC//60} min)")

    result = subprocess.run(
        cmd, cwd=str(RESEARCH_DIR), capture_output=True, text=True,
        env=env, timeout=ANALYSIS_TIMEOUT_SEC
    )

    if result.returncode != 0:
        state["error"] = f"run_all.py failed (exit code {result.returncode})"
        state["analysis_success"] = False
        print(f"  [FAIL] {state['error']}")
        if result.stderr:
            print(f"  STDERR (last 20 lines):")
            for ln in result.stderr.strip().splitlines()[-20:]:
                print(f"    {ln}")
        return state

    lines = result.stdout.strip().splitlines()
    print(f"  Output: {len(lines)} lines")
    for ln in lines[-30:]:
        print(f"    {ln}")

    guard_updated = False
    if EDGE_GUARD_CONFIG.exists():
        guard_mtime_after = EDGE_GUARD_CONFIG.stat().st_mtime
        if guard_mtime_before is None or guard_mtime_after > guard_mtime_before:
            guard_updated = True

    state["analysis_success"] = True
    state["guard_updated"] = guard_updated
    state["last_step"] = "run_analysis"
    print(f"  [OK] Analysis complete. VPEdgeGuard updated: {guard_updated}")
    return state


def verify_guards(state: dict) -> dict:
    """Verify VPEdgeGuardConfig.mqh is valid and was regenerated."""
    print("\n" + "=" * 60)
    print("  STEP: VERIFY VP EDGEGUARD")
    print("=" * 60)

    if not state.get("analysis_success"):
        state["error"] = "Skipping verify — analysis failed"
        state["guards_valid"] = False
        print(f"  [SKIP] {state['error']}")
        return state

    if not EDGE_GUARD_CONFIG.exists():
        state["error"] = "VPEdgeGuardConfig.mqh not found"
        state["guards_valid"] = False
        print(f"  [FAIL] {state['error']}")
        return state

    content = EDGE_GUARD_CONFIG.read_text(encoding="utf-8", errors="replace")
    lines = content.splitlines()

    has_header    = any("__VP_EA_EDGEGUARD_CONFIG_MQH__" in ln for ln in lines[:5])
    has_endif     = any("#endif" in ln for ln in lines[-5:])
    has_functions = (
        "VPIsBlocked" in content and
        "VPGetEdgeMultiplier" in content and
        "VPGetLotMultiplier" in content
    )

    valid = has_header and has_endif and has_functions
    state["guards_valid"] = valid
    state["guard_lines"] = len(lines)
    state["last_step"] = "verify_guards"

    if valid:
        print(f"  [OK] VPEdgeGuardConfig.mqh valid ({len(lines)} lines)")
    else:
        state["error"] = "VPEdgeGuardConfig.mqh validation failed"
        print(f"  [FAIL] header={has_header} endif={has_endif} functions={has_functions}")

    return state


# ─── Helper: Move backtest report ────────────────────────────────────────────

def _move_backtest_report():
    import shutil
    BACKTEST_REPORT_DIR.mkdir(parents=True, exist_ok=True)

    search_patterns = [
        MT5_DATA_DIR / "backtest_report.xml",
        MT5_DATA_DIR / "backtest_report.htm",
        MT5_DATA_DIR / "backtest_report.html",
    ]

    moved = False
    for src in search_patterns:
        if src.exists():
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            dest = BACKTEST_REPORT_DIR / f"backtest_{timestamp}{src.suffix}"
            shutil.move(str(src), str(dest))
            print(f"  Report moved: {src.name} → {dest}")
            moved = True

    if not moved:
        for pattern in ["backtest_report*", "*.xml"]:
            for f in MT5_DATA_DIR.glob(pattern):
                if f.is_file() and f.stat().st_size > 1000:
                    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                    dest = BACKTEST_REPORT_DIR / f"backtest_{timestamp}{f.suffix}"
                    shutil.move(str(f), str(dest))
                    print(f"  Report moved: {f.name} → {dest}")
                    moved = True
                    break

    if not moved:
        print("  [INFO] No backtest report found to move")


# ─── Helper: Generate tester .ini ────────────────────────────────────────────

def _generate_tester_ini() -> Path:
    """Create a tester .ini for MT5 CLI backtest of VP EA."""
    cfg = BACKTEST_CONFIG

    experts_dir = MT5_DATA_DIR / "MQL5" / "Experts"
    ea_ex5 = MAIN_EA_SOURCE.with_suffix(".ex5")
    try:
        ea_relative = ea_ex5.relative_to(experts_dir)
        ea_path = str(ea_relative).replace("/", "\\")
    except ValueError:
        ea_path = str(ea_ex5).replace("/", "\\")

    ini_content = f"""[Tester]
Expert={ea_path}
Symbol={cfg['symbol']}
Period={cfg['period']}
FromDate={cfg['from_date']}
ToDate={cfg['to_date']}
Model={cfg['model']}
Deposit={cfg['deposit']}
Leverage={cfg['leverage']}
Optimization={cfg['optimization']}
OptimizationCriterion={cfg.get('optimization_criterion', 6)}
ForwardMode={cfg.get('forward_mode', 0)}
ShutdownTerminal=1
Visual=0
UseMarketWatch=1
ReplaceReport=1
Report=backtest_report
"""
    if cfg.get("ea_input_file"):
        set_file = Path(__file__).parent / cfg["ea_input_file"]
        if set_file.exists():
            ini_content += f"ExpertParameters={set_file}\n"
            print(f"  Using .set file: {set_file.name}")
        else:
            print(f"  [WARN] .set file not found: {set_file}")

    ini_path = Path(__file__).parent / "tester_config.ini"
    ini_path.write_text(ini_content, encoding="utf-8")
    print(f"  INI content:")
    for line in ini_content.strip().splitlines():
        print(f"    {line}")
    return ini_path
